# Generated by Django 6.0.3 on 2026-03-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('graduation_school', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('residency_graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('professional_degree', models.CharField(blank=True, max_length=255)),
                ('professional_degree_year', models.PositiveIntegerField(blank=True, null=True)),
                ('academic_degree', models.CharField(blank=True, max_length=255)),
                ('academic_degree_year', models.PositiveIntegerField(blank=True, null=True)),
                ('thesis_topic', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('membership_type', models.CharField(choices=[('resident', 'Resident'), ('specialist', 'Specialist'), ('international', 'International')], default='specialist', max_length=20)),
                ('is_active_member', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
